services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cars
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", '-h', 'localhost', "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      db: 
        condition: service_healthy
  
  api:
    build: ./api
    restart: unless-stopped
    ports: 
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: cars
      JWT_SECRET: KSD0ckT3AnkOXRCoZRV7iEDDgolLl6mtPlHO61jns3D
      CORS_ORIGIN: http://localhost:5173
    depends_on:
      db: 
        condition: service_healthy
  
  front:
    build: ./front
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - api

volumes:
  mysql_data: